.TH "ECUAL/Button driver/Button.c" 3 "Fri Aug 12 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECUAL/Button driver/Button.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./Service/ATmega32Port\&.h'\fP
.br
\fC#include 'Button\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEN_pinErro_t\fP \fBbuttonInit\fP (\fBEN_pinNum_t\fP buttonPin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEN_pinErro_t\fP buttonInit (\fBEN_pinNum_t\fP buttonPin)"

.PP
Definition at line \fB11\fP of file \fBButton\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
