.TH "Service/dataTypes.h" 3 "Fri Aug 12 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Service/dataTypes.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBsint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef signed short int \fBsint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef signed long int \fBsint32_t\fP"
.br
.ti -1c
.RI "typedef float \fBfloat32_t\fP"
.br
.ti -1c
.RI "typedef double \fBfloat64_t\fP"
.br
.ti -1c
.RI "typedef long double \fBfloat128_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef long double \fBfloat128_t\fP"

.PP
Definition at line \fB18\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef float \fBfloat32_t\fP"

.PP
Definition at line \fB16\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef double \fBfloat64_t\fP"

.PP
Definition at line \fB17\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef signed short int \fBsint16_t\fP"

.PP
Definition at line \fB13\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef signed long int \fBsint32_t\fP"

.PP
Definition at line \fB15\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef signed char \fBsint8_t\fP"

.PP
Definition at line \fB11\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef unsigned short int \fBuint16_t\fP"

.PP
Definition at line \fB12\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef unsigned long int \fBuint32_t\fP"

.PP
Definition at line \fB14\fP of file \fBdataTypes\&.h\fP\&.
.SS "typedef unsigned char \fBuint8_t\fP"

.PP
Definition at line \fB10\fP of file \fBdataTypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
