.TH "MCAL/Dio driver/DIO.h" 3 "Fri Aug 12 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCAL/Dio driver/DIO.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./Service/ATmega32Port\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./Service/BitMath\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./Service/dataTypes\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./Service/RegisterFile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEN_pinErro_t\fP \fBDIO_pinInit\fP (\fBEN_pinNum_t\fP pinNum, \fBEN_pinDirection_t\fP pinDirection)"
.br
.ti -1c
.RI "\fBEN_pinErro_t\fP \fBDIO_pinWrite\fP (\fBEN_pinNum_t\fP pinNum, \fBEN_pinState_t\fP pinState)"
.br
.ti -1c
.RI "\fBEN_pinErro_t\fP \fBDIO_pinToggle\fP (\fBEN_pinNum_t\fP pinNum)"
.br
.ti -1c
.RI "\fBEN_pinErro_t\fP \fBDIO_pinRead\fP (\fBEN_pinNum_t\fP pinNum, \fBEN_pinState_t\fP *pinState)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEN_pinErro_t\fP DIO_pinInit (\fBEN_pinNum_t\fP pinNum, \fBEN_pinDirection_t\fP pinDirection)"

.PP
Definition at line \fB12\fP of file \fBDIO\&.c\fP\&.
.SS "\fBEN_pinErro_t\fP DIO_pinRead (\fBEN_pinNum_t\fP pinNum, \fBEN_pinState_t\fP * pinState)"

.PP
Definition at line \fB166\fP of file \fBDIO\&.c\fP\&.
.SS "\fBEN_pinErro_t\fP DIO_pinToggle (\fBEN_pinNum_t\fP pinNum)"

.PP
Definition at line \fB198\fP of file \fBDIO\&.c\fP\&.
.SS "\fBEN_pinErro_t\fP DIO_pinWrite (\fBEN_pinNum_t\fP pinNum, \fBEN_pinState_t\fP pinState)"

.PP
Definition at line \fB90\fP of file \fBDIO\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
