.TH "Service/RegisterFile.h" 3 "Fri Aug 12 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Service/RegisterFile.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORTA\fP   (*((volatile \fBuint8_t\fP*)0x3B))"
.br
.ti -1c
.RI "#define \fBDDRA\fP   (*((volatile \fBuint8_t\fP*)0x3A))"
.br
.ti -1c
.RI "#define \fBPINA\fP   (*((volatile \fBuint8_t\fP*)0x39))"
.br
.ti -1c
.RI "#define \fBPORTB\fP   (*((volatile \fBuint8_t\fP*)0x38))"
.br
.ti -1c
.RI "#define \fBDDRB\fP   (*((volatile \fBuint8_t\fP*)0x37))"
.br
.ti -1c
.RI "#define \fBPINB\fP   (*((volatile \fBuint8_t\fP*)0x36))"
.br
.ti -1c
.RI "#define \fBPORTC\fP   (*((volatile \fBuint8_t\fP*)0x35))"
.br
.ti -1c
.RI "#define \fBDDRC\fP   (*((volatile \fBuint8_t\fP*)0x34))"
.br
.ti -1c
.RI "#define \fBPINC\fP   (*((volatile \fBuint8_t\fP*)0x33))"
.br
.ti -1c
.RI "#define \fBPORTD\fP   (*((volatile \fBuint8_t\fP*)0x32))"
.br
.ti -1c
.RI "#define \fBDDRD\fP   (*((volatile \fBuint8_t\fP*)0x31))"
.br
.ti -1c
.RI "#define \fBPIND\fP   (*((volatile \fBuint8_t\fP*)0x30))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDRA   (*((volatile \fBuint8_t\fP*)0x3A))"

.PP
Definition at line \fB17\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define DDRB   (*((volatile \fBuint8_t\fP*)0x37))"

.PP
Definition at line \fB22\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define DDRC   (*((volatile \fBuint8_t\fP*)0x34))"

.PP
Definition at line \fB27\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define DDRD   (*((volatile \fBuint8_t\fP*)0x31))"

.PP
Definition at line \fB32\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PINA   (*((volatile \fBuint8_t\fP*)0x39))"

.PP
Definition at line \fB18\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PINB   (*((volatile \fBuint8_t\fP*)0x36))"

.PP
Definition at line \fB23\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PINC   (*((volatile \fBuint8_t\fP*)0x33))"

.PP
Definition at line \fB28\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PIND   (*((volatile \fBuint8_t\fP*)0x30))"

.PP
Definition at line \fB33\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PORTA   (*((volatile \fBuint8_t\fP*)0x3B))"

.PP
Definition at line \fB16\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PORTB   (*((volatile \fBuint8_t\fP*)0x38))"

.PP
Definition at line \fB21\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PORTC   (*((volatile \fBuint8_t\fP*)0x35))"

.PP
Definition at line \fB26\fP of file \fBRegisterFile\&.h\fP\&.
.SS "#define PORTD   (*((volatile \fBuint8_t\fP*)0x32))"

.PP
Definition at line \fB31\fP of file \fBRegisterFile\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
